apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: team-pegasus
commonAnnotations:
  enzo: "true"
resources:
  - web-deployment.yaml
  - web-service.yaml
  - web-route.yaml